version: "3.9"

services:
  api:
    build: .
    hostname: genshin.api
    volumes:
      - ./app:/usr/src/app
    command: "sh start_script.sh"
    env_file:
      - github.env
    networks:
      - api_network
      - database_network
    ports:
      - 80:80
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 20M
    restart: always
    networks:
      - database_network

  tunnel:
    restart: always
    depends_on:
      - api
    image: cloudflare/cloudflared
    command: tunnel run
    networks:
      - api_network
    env_file:
      - ./env/cloudflared.env

networks:
  database_network:
  api_network:
    external: true
